### PR TITLE
changes for #271

### PR DESCRIPTION
**Pull request by phongnt**
#271

### CODE REVIEW

**Comment by callmekatootie** [comment]
@phongnt 

> Expected: Trim the values entered in the input fields - general **as well as custom attributes** DURING saving of the changes made.

The changes have not been carried out for custom attributes

**Comment by phongnt** [comment]
I got your idea. It’s easy to implement. I busy now. Please give me time for updating.

**Comment by callmekatootie** [comment]
Ok

**Comment by callmekatootie** [comment]
@phongnt Can you please let me know if you have started working on this - if you are still caught up with other stuff, I would like to open this for others to work on...

**Comment by callmekatootie** [comment]
@phongnt I am afraid the issue is still not resolved...

image

For the above fields, when I type spaces - the values are not trimmed and they are still saved...

**Comment by callmekatootie** [comment]
I am afraid I will have to open the ticket for others to work on

**Pull request closed without merging**
