### PR TITLE
Fix logout dropdown hide on outside click

### PR DESCRIPTION
**Pull request by sanju-singh**
#45

### CODE REVIEW

**Comment by callmekatootie** [comment]
Before fix:

image

After fix:

image

There's a bolder outline...

**Comment by sanju-singh** [comment]
That is because, earlier that dropdown was not getting focused, thats the behaviour of focus. It will work in accessibility behaviour as well, like going through tab hitting tab will focus the dropdown itself.

**Comment by callmekatootie** [comment]
> That is because, earlier that dropdown was not getting focused, thats the behaviour of focus. It will work in accessibility behaviour as well, like going through tab hitting tab will focus the dropdown itself.

Ok. But we are not expecting any focus to happen - the expectation is that the dropdown closes when clicked outside. It should not have any side effects

**Comment by sanju-singh** [comment]
This is the only clean solution I found. others require focus on top document, and may not work always

**Comment by callmekatootie** [comment]
I see. Could we then disable the outline using CSS when the element is in focus...

**Comment by sanju-singh** [comment]
ok, I will update the css.

**Comment by callmekatootie** [comment]
@sanju-singh Is this ready for review again... (If so, remove the Feedback label to get my attention :blush:  )

**Comment by sanju-singh** [comment]
@callmekatootie , yes, I updated in issue, forgot to update here. Thanks

**Pull request merged**
