### PR TITLE
issue 46 fix

### LINKED ISSUE #46: [$20] Group details touching layout on Edit profile page for profile
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Edit icon on profile "Aang Airbender"
3) Edit profile page open
4) Observe Groups on left land side

Current Result :
Group details touching layout 

Expected result:
Group details should not touch layout 

Latest Firefox
Windows 10

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
#46

### CODE REVIEW

**Comment by PrakashDurlabhji** [comment]
@callmekatootie yes i increased a bit padding, i will reset to original one. and  i will paste a verification screenshot for the fix now. It was visible and working in edit profile.

**Comment by PrakashDurlabhji** [comment]
@callmekatootie screenshot 
Capture

**Comment by callmekatootie** [comment]
@PrakashDurlabhji The changes are incorrect. You have used word break but you were expected to only reduce the width of the pill. Please see this: https://github.com/topcoder-platform/u-bahn-app/issues/46#issuecomment-663144266

I am afraid that if this does not get resolved in the next 2 hours, I will have to open this for others to pickup

**Comment by PrakashDurlabhji** [comment]
@callmekatootie in 1 hour i will complete

**Comment by PrakashDurlabhji** [comment]
@callmekatootie can you please check again? I updated

**Comment by callmekatootie** [comment]
@PrakashDurlabhji I am afraid the fix is not acceptable - you have shrunk the pill size but that is not the right way to go about it - the pill size should take up the container size it is in and have a max width... shrinking the max width would not be a good solution

**Comment by PrakashDurlabhji** [comment]
@callmekatootie i can solve this but break-word is required if we want to show full text. or i need to show ellipsis? is ellipsis ok?

**Comment by callmekatootie** [comment]
Right now, ellipsis is being showed.

The fix expected is that the pill should have a max width (which it does currently and it is fine) AND if the container in which the pill exists is having a shorter width, the pill should not exceed the container's width

**Comment by PrakashDurlabhji** [comment]
@callmekatootie yes understood, now you will be satisfied with my approach. updating it

**Comment by PrakashDurlabhji** [comment]
@callmekatootie will this be ok? as i cannot control child pills width also you said i cannot alter pill css,so i have to apply changes to parent div

Capture

**Comment by callmekatootie** [comment]
No, I am afraid that is not acceptable.

You can alter the Pill CSS - but not my playing with it's max width property...

**Pull request closed without merging**
