### PR TITLE
Issue #473 fixes.

### PR DESCRIPTION
**Pull request by venkygot**
#473 Fixes given. Kindly review

### CODE REVIEW

**Comment by venkygot** [comment]
@callmekatootie Thanks for the feedback. Let me see what I can do on this.

**Comment by callmekatootie** [comment]
You can check out the code for when you open the Add To Group modal and close it before the data loads - requests are cancelled here too... But in this case, the code was elegant

**Comment by callmekatootie** [comment]
Also - don't forget to pull latest code and keep your base branch in sync

**Comment by venkygot** [comment]
@callmekatootie there is an open issue in react for this https://github.com/facebook/react/issues/15006. The error happens only once but not on every unmount I debugged using console logs. Not sure how to go about it in fixing it. Any thoughts?

**Comment by callmekatootie** [comment]
@venkygot I would like to open this for others to work on.

In case nobody comes with a satisfactory solution, we can take a call then on how to proceed.

**Comment by venkygot** [comment]
@callmekatootie fair enough

**Comment by venkygot** [comment]
@callmekatootie console error should be fixed now. just missed something

**Pull request merged**
