### PR TITLE
fixes issue#66

### PR DESCRIPTION
**Pull request by romitgithub**
https://github.com/topcoder-platform/u-bahn-app/issues/66

### CODE REVIEW

**Comment by callmekatootie** [comment]
@romitgithub The previous PR was not merged since it did not fix the issue - you have to submit all the changes, in this case, the changes in the Search page too...

**Comment by callmekatootie** [comment]
@romitgithub Sorry but the changes are not fine - the scroll happens AFTER the results appear - the scroll should happen when search is invoked... That is, if I change the page number, it should immediately scroll to the top...

**Comment by romitgithub** [comment]
@callmekatootie The issue is on Global Search Page only, right? The groups page is fine?

**Comment by callmekatootie** [comment]
I would say no - even the groups page needs the scroll to happen before the search starts... Right now, the members load and then the scroll happens...

**Comment by romitgithub** [comment]
@callmekatootie Done. It scrolls before loading members now in both pages. Please verify. Thanks

**Pull request merged**
